#!/bin/bash
CUDA_VISIBLE_DEVICES=1 python sample.py configs/recon/airplane_v3.yaml --pretrained  pretrained/recon/airplane_v3_2021-Sep-03-13-08-15/checkpoints/epoch_450_iters_0.pt
CUDA_VISIBLE_DEVICES=1 python sample.py configs/recon/chair_v3.yaml --pretrained  pretrained/recon/chair_v3_2021-Sep-03-13-08-49/checkpoints/epoch_450_iters_0.pt
CUDA_VISIBLE_DEVICES=1 python sample.py configs/recon/car_v3.yaml --pretrained  pretrained/recon/car_v3_2021-Sep-03-15-34-32/checkpoints/epoch_450_iters_0.pt
