data:
  type: datasets.pointflow_datasets_v2
  dataset_type: shapenet15k
  num_workers: 16
  cates: ['airplane']
  tr_max_sample_points: 2048
  te_max_sample_points: 2048
  data_dir: data/ShapeNetCore.v2.PC15k
  batch_size: 48
  # batch_size: 96
  dataset_scale: 1
  normalize_per_shape: False
  normalize_std_per_axis: False
  recenter_per_shape: True
  fps: True

viz:
  save_freq: 10
  log_freq: 10
  viz_freq: 10
  val_freq: 10

trainer:
  type: trainers.stylegan_trainer_v2
  ae_pretrained: '/home/yunfan/Star-Net/pretrained/airplane/checkpoints/epoch_450_iters_0.pt'
  epochs: 1001
  seed: 100

  # For autoencoding
  validate_recon: True
  opt_dec:
    type: 'adam'
    lr: 1e-4
    beta1: 0.5
    beta2: 0.9
    weight_decay: 0.
  opt_enc:
    type: 'adam'
    lr: 1e-4
    beta1: 0.5
    beta2: 0.9
    weight_decay: 0.

  # For GAN
  gan_only: True
  gan_loss_type: "wgan"
  # Gradient penalty
  gp_weight: 1.
  gp_type: 'zero_center'
  n_critics: 5
  opt_gen:
    type: 'adam'
    lr: 1e-3
    beta1: 0.5
    beta2: 0.99
    step: False
    scheduler: step
    step_epoch: 50
    weight_decay: 0.
  opt_dis:
    type: 'adam'
    lr: 1e-4
    beta1: 0.5
    beta2: 0.999
    scheduler: step
    step_epoch: 2000
    step_decay: 0.5
    weight_decay: 0.
  # opt_dis:
  #   type: 'adam'
  #   lr: 1e-3
  #   beta1: 0.5
  #   beta2: 0.99
  #   step: False
  #   weight_decay: 0.

models:
  # For auto-encoder
  decoder:  # [dim] - [hid_dims] - [dim]
    type: models.decoders.sparenet_decoder
    dim: 3
    out_dim: 3
    z_dim: 128
  encoder:
    type: models.encoders.l3dp_encoder_v2
    use_deterministic_encoder: True
    zdim: 128
    input_dim: 3

  # For latent GAN
  gen:
    type: models.generators.mlp_gen
    # z_dim: 128
    inp_dim: 128
    out_dim: 128
    dims:
      # - 256
      # - 256
      - 128
      - 128
      - 128
    prior: gaussian
    gaussian_scale: 1.
    use_bn: True
  # dis:
  #   type: models.discriminators.mlp_dis
  #   inp_dim: 128
  #   dims:
  #     - 512
  #     - 512
  #   use_bn: False
  #   use_ln: False
  #   use_sigmoid: False
  dis:
    type: models.discriminators.stylegan_dis
    num_pts: 2048
    features: [3, 64, 128, 256, 512, 1024]

inference:
  step_size_ratio: 1
  num_steps: 10
  num_points: 2048
  weight: 1
