#!/bin/bash
python \
train.py \
"./archive/airplane_220721_2021-Jul-23-15-45-52/config/airplane_250721.yaml" \
--resume \
--pretrained "./archive/airplane_220721_2021-Jul-23-15-45-52/checkpoints/epoch_3900_iters_0.pt"
