data:
  type: datasets.pointflow_datasets_v2
  dataset_type: shapenet15k
  num_workers: 16
  cates: ['airplane']
  tr_max_sample_points: 2048
  te_max_sample_points: 2048
  data_dir: data/ShapeNetCore.v2.PC15k
  batch_size: 512
  dataset_scale: 1
  normalize_per_shape: False
  normalize_std_per_axis: False
  recenter_per_shape: True
  fps: True

viz:
  save_freq: 100
  log_freq: 100
  viz_freq: 400
  val_freq: 100

trainer:
  # type: trainers.lgan_trainer_3D_v2
  type: trainers.lgan_trainer_3D
  epochs: 10001
  seed: 100
  val_metrics_batch_size: 400
  max_gen_validate_shapes: 607

  # For autoencoding
  validate_recon: True
  opt_dec:
    type: 'adam'
    lr: 1e-4
    beta1: 0.5
    beta2: 0.9
    weight_decay: 0.
  opt_enc:
    type: 'adam'
    lr: 1e-4
    beta1: 0.5
    beta2: 0.9
    weight_decay: 0.

  # For GAN
  ae_pretrained: '/home/yunfan/workarea/stylegan_pcgen.v1/pretrained/recon/airplane_v3_2021-Sep-03-13-08-15/checkpoints/epoch_450_iters_0.pt'
  gan_only: True
  gan_loss_type: "wgan"
  # Gradient penalty
  gp_weight: 1.
  gp_type: 'zero_center'
  n_critics: 1
  opt_gen:
    type: 'adam'
    lr: 1e-4
    beta1: 0.5
    beta2: 0.99
    step: False
    weight_decay: 0.
  opt_dis:
    type: 'adam'
    lr: 1e-4
    beta1: 0.5
    beta2: 0.99
    step: False
    weight_decay: 0.

models:
  # For auto-encoder
  decoder:  # [dim] - [hid_dims] - [dim]
    type: models.decoders.sparenet_decoder
    dim: 3
    out_dim: 3
    z_dim: 128
  encoder:
    type: models.encoders.l3dp_encoder_v2
    use_deterministic_encoder: True
    zdim: 128
    input_dim: 3

  # For latent GAN
  gen:
    type: models.generators.mlp_gen
    inp_dim: 128
    out_dim: 128
    dims:
      # - 256
      # - 256
      - 128
      - 128
      - 128
    prior: gaussian
    gaussian_scale: 1.
    use_bn: False
    use_bn: True
    # output_bn: False
  dis:
    type: models.discriminators.mlp_dis
    inp_dim: 128
    dims:
      - 512
      - 512
    use_bn: False
    use_ln: False
    use_sigmoid: False

inference:
  step_size_ratio: 1
  num_steps: 10
  num_points: 2048
  weight: 1
